local is_tty = vim.fn.has('unix') == 1 and vim.env.TERM == 'linux'
require('pluginstaller')
require('config.cmpConfig')
require('config.lspConfig')
require('config.otherConfig')
require('config.iblConfig')
require('config.tree')
require('config.autoPair')
require('config.troubleShow')
require('config.imSelect')
require('config.lspEnhance')
require('config.masonConfig')
require('config.alphanvim')
require('config.lualine')
require('config.lspsaga')
